import type { Static } from '@feathersjs/typebox';
import type { HookContext } from '../../declarations';
export declare const companySchema: import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TNumber;
    name: import("@sinclair/typebox").TString<string>;
    status: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    createdAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    gstNumber: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    invoiceType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    address: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    city: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    contactName: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    contactEmail: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    contactPhone: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    margin: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
}>;
export type Company = Static<typeof companySchema>;
export declare const companyValidator: import("@feathersjs/schema").Validator<any, any>;
export declare const companyResolver: import("@feathersjs/schema").Resolver<{
    status?: string | undefined;
    createdAt?: string | undefined;
    gstNumber?: string | undefined;
    invoiceType?: string | undefined;
    address?: string | undefined;
    city?: string | undefined;
    contactName?: string | undefined;
    contactEmail?: string | undefined;
    contactPhone?: string | undefined;
    margin?: string | undefined;
    name: string;
    id: number;
}, HookContext>;
export declare const companyExternalResolver: import("@feathersjs/schema").Resolver<{
    status?: string | undefined;
    createdAt?: string | undefined;
    gstNumber?: string | undefined;
    invoiceType?: string | undefined;
    address?: string | undefined;
    city?: string | undefined;
    contactName?: string | undefined;
    contactEmail?: string | undefined;
    contactPhone?: string | undefined;
    margin?: string | undefined;
    name: string;
    id: number;
}, HookContext>;
export declare const companyDataSchema: import("@sinclair/typebox").TObject<{
    name: import("@sinclair/typebox").TString<string>;
    status: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    createdAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    gstNumber: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    invoiceType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    address: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    city: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    contactName: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    contactEmail: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    contactPhone: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    margin: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
}>;
export type CompanyData = Static<typeof companyDataSchema>;
export declare const companyDataValidator: import("@feathersjs/schema").Validator<any, any>;
export declare const companyDataResolver: import("@feathersjs/schema").Resolver<{
    status?: string | undefined;
    createdAt?: string | undefined;
    gstNumber?: string | undefined;
    invoiceType?: string | undefined;
    address?: string | undefined;
    city?: string | undefined;
    contactName?: string | undefined;
    contactEmail?: string | undefined;
    contactPhone?: string | undefined;
    margin?: string | undefined;
    name: string;
}, HookContext>;
export declare const companyPatchSchema: import("@sinclair/typebox").TPartial<import("@sinclair/typebox").TObject<{
    name: import("@sinclair/typebox").TString<string>;
    status: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    createdAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    gstNumber: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    invoiceType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    address: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    city: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    contactName: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    contactEmail: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    contactPhone: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    margin: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
}>>;
export type CompanyPatch = Static<typeof companyPatchSchema>;
export declare const companyPatchValidator: import("@feathersjs/schema").Validator<any, any>;
export declare const companyPatchResolver: import("@feathersjs/schema").Resolver<Partial<{
    status?: string | undefined;
    createdAt?: string | undefined;
    gstNumber?: string | undefined;
    invoiceType?: string | undefined;
    address?: string | undefined;
    city?: string | undefined;
    contactName?: string | undefined;
    contactEmail?: string | undefined;
    contactPhone?: string | undefined;
    margin?: string | undefined;
    name: string;
}>, HookContext>;
export declare const companyQuerySchema: import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
    name: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    status: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    createdAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    gstNumber: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    invoiceType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    address: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    city: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    contactName: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    contactEmail: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    contactPhone: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    margin: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString<string>>;
    $limit: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
    $skip: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
    $sort: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{}>>;
    $select: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString<string>>>;
}>;
export type CompanyQuery = Static<typeof companyQuerySchema>;
export declare const companyQueryValidator: import("@feathersjs/schema").Validator<any, any>;
export declare const companyQueryResolver: import("@feathersjs/schema").Resolver<{
    name?: string | undefined;
    id?: number | undefined;
    $limit?: number | undefined;
    status?: string | undefined;
    createdAt?: string | undefined;
    gstNumber?: string | undefined;
    invoiceType?: string | undefined;
    address?: string | undefined;
    city?: string | undefined;
    contactName?: string | undefined;
    contactEmail?: string | undefined;
    contactPhone?: string | undefined;
    margin?: string | undefined;
    $skip?: number | undefined;
    $sort?: {} | undefined;
    $select?: string[] | undefined;
}, HookContext>;
