var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(app)/support/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0wkc0f6._.js")
R.c("server/chunks/ssr/node_modules_0sy8gnb._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_11rg0yu.js")
R.c("server/chunks/ssr/[root-of-the-server]__037jk45._.js")
R.c("server/chunks/ssr/node_modules_next_dist_03nkrli._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0mmjv-k._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/apps_web_src_07d_ag4._.js")
R.c("server/chunks/ssr/apps_web__next-internal_server_app_(app)_support_page_actions_0q2da_s.js")
R.m(21269)
module.exports=R.m(21269).exports
