import type { Config } from "tailwindcss";
import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        outline: "#737686",
        "surface-container": "#eceef0",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#ffb690",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        background: "#f7f9fb",
        "tertiary-fixed": "#ffdbcd",
        "outline-variant": "#c3c6d7",
        "on-primary-fixed": "#00174b",
        "error-container": "#ffdad6",
        "secondary-fixed": "#ffdbca",
        surface: "#f7f9fb",
        "inverse-surface": "#2d3133",
        primary: "#004ac6",
        "primary-fixed": "#dbe1ff",
        tertiary: "#943700",
        "surface-variant": "#e0e3e5",
        "on-primary-fixed-variant": "#003ea8",
        "primary-container": "#2563eb",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#ffede6",
        "inverse-primary": "#b4c5ff",
        error: "#ba1a1a",
        "primary-fixed-dim": "#b4c5ff",
        "on-tertiary-fixed-variant": "#7d2d00",
        secondary: "#9d4300",
        "surface-container-high": "#e6e8ea",
        "surface-tint": "#0053db",
        "secondary-container": "#fd761a",
        "surface-container-low": "#f2f4f6",
        "on-surface-variant": "#434655",
        "on-primary-container": "#eeefff",
        "on-secondary-fixed-variant": "#783200",
        "surface-dim": "#d8dadc",
        "surface-bright": "#f7f9fb",
        "on-background": "#191c1e",
        "tertiary-fixed-dim": "#ffb596",
        "on-secondary-container": "#5c2400",
        "on-surface": "#191c1e",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary-fixed": "#360f00",
        "surface-container-highest": "#e0e3e5",
        "tertiary-container": "#bc4800",
        "on-secondary-fixed": "#341100",
        "on-primary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-manrope)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"],
      },
    },
  },
  plugins: [
    forms,
    containerQueries,
  ],
};
export default config;
